---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bitnami.yaml
  - k8s-at-home-charts.yaml
  - nfs-subdir-external-provisioner-charts.yaml
  - prometheus-community-charts.yaml
