---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mopidy-config
  namespace: home
data:
  mopidy.conf: |
    # For information about configuration values that can be set in this file see:
    #
    #   https://docs.mopidy.com/en/latest/config/
    #
    # Run `sudo mopidyctl config` to see the current effective config, based on
    # both defaults and this configuration file.

    [audio]
    output = lamemp3enc bitrate=320 ! shout2send async=false mount=listen ip=mopidy-icecast port=8000 password=${SECRET_ICECAST_PASSWORD}

    [gmusic]
    enabled = false

    [http]
    hostname = 0.0.0.0
    default_app = iris

    [iris]
    country = US
    locale = en_US

    [pandora]
    enabled = false

    [party]
    enabled = true
    votes_to_skip = 2

    [spotify]
    username = ${SECRET_SPOTIFY_USERNAME}
    password = ${SECRET_SPOTIFY_PASSWORD}
    client_id = ${SECRET_MOPIDY_SPOTIFY_CLIENT_ID}
    client_secret = ${SECRET_MOPIDY_SPOTIFY_CLIENT_SECRET}
    bitrate = 320
    toplist_countries = US

    [soundcloud]
    enabled = false
