---

- hosts:
  - fileserver
  become: true
  roles:
  - role: geerlingguy.nfs
    nfs_exports: ["/mnt/share 192.168.1.0/24(rw,no_subtree_check)"]
  tasks:
  - name: Disable password login
    user:
      name: debian
      password_lock: true
  - name: Set share directory permissions
    file:
      path: /mnt/share
      owner: nobody
      group: nogroup
